name: coin_one
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  shared_preferences: ^2.2.3

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

